// Escenarios del brief. Todo lo que no tiene campo propio en Torq va en el texto
// del objetivo (el único texto libre del formulario de crear plan) o en
// "lesiones" (perfil). FC máx: el perfil la exige; sin dato se deja el default
// de la app (185).
import { addDays, fmtLong, todayKey } from './lib.mjs';

const inWeeks = (n) => fmtLong(addDays(todayKey(), n * 7));

// fb = retro de la semana: completed (fracción), rpeDelta (vs. lo planeado), notas, señales por zona
export const SCENARIOS = {
  1: {
    title: 'XCO × novato', age: 24, weight: 70, sex: null, ftp: null, hrMax: 185, discipline: 'mountain',
    experienceLevel: 'new_to_cycling', generalFitnessLevel: 'active_other_sport', yearsRiding: 0.5, competes: true, category: 'Novatos',
    hours: 5, days: ['mon', 'wed', 'fri', 'sat'], maxMin: null, injuries: null,
    goal: () => `Mi primera carrera de XCO es el ${inWeeks(12)} (en 12 semanas). Soy novato. Mi cadencia natural es de 65-70 rpm. No sé mi FTP ni mi frecuencia cardiaca máxima.`,
    truthFtp: 190, best1Min: 255,
    fb: { note: 'Completé todo, pero me costó mucho mantener 85+ rpm.', rpe: 'as_planned', cadenceFloorHits: 6 },
  },
  2: {
    title: 'Maratón MTB × fondista que se funde', age: 38, weight: 82, sex: null, ftp: null, hrMax: 185, discipline: 'mountain',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 5, competes: true, category: 'Master 30',
    hours: 7, days: ['tue', 'thu', 'sat', 'sun'], maxMin: null, injuries: null,
    goal: () => `Maratón MTB tipo Chupacabras (~100 km) el ${inWeeks(14)} (en 14 semanas). Termino las rodadas largas pero me fundo después de unas 2.5 horas. No sé mi FTP.`,
    truthFtp: 235, best1Min: 315,
    fb: { note: 'Completé todo. En la rodada larga la FC se fue alta desde el inicio.', rpe: 'as_planned', longRideHrStartHigh: true },
  },
  3: {
    title: 'Ruta × FTP inflado', age: 33, weight: 74, sex: null, ftp: 290, ftpAgeDays: 60, hrMax: 185, discipline: 'road',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 6, competes: false, category: null,
    hours: 8, days: ['mon', 'wed', 'thu', 'sat', 'sun'], maxMin: null, injuries: null,
    goal: () => 'Mejorar mi rendimiento general en ruta. Sin evento. Mi FTP de 290 W lo saqué de otra app.',
    truthFtp: 250, best1Min: 335,
    fb: { note: 'En las sesiones de Z2 la FC estuvo en 158-165 bpm y el esfuerzo se sintió 7/10.', z2Hr: [158, 165], z2Rpe: 7, hrCeilingHits: 4 },
  },
  4: {
    title: 'Gravel × poco tiempo', age: 41, weight: 78, sex: null, ftp: 230, ftpAgeDays: 30, hrMax: 185, discipline: 'gravel',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 8, competes: false, category: null,
    hours: 4.25, days: ['tue', 'wed', 'thu', 'sat'], maxMin: null, injuries: null,
    goal: () => `Gravel de 120 km el ${inWeeks(10)} (en 10 semanas). Entre semana solo tengo 3 sesiones de 45 min (mar, mié, jue) y el sábado una salida de 2 h.`,
    truthFtp: 230, best1Min: 310,
    fb: { note: 'Completé todo.', rpe: 'as_planned' },
  },
  5: {
    title: 'Enduro × explosivo sin fondo', age: 29, weight: 72, sex: null, ftp: 240, ftpAgeDays: 30, hrMax: 185, discipline: 'mountain',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 4, competes: true, category: 'Enduro amateur',
    hours: 5, days: ['tue', 'thu', 'sat', 'sun'], maxMin: null, injuries: null,
    goal: () => `Carrera de enduro el ${inWeeks(10)} (en 10 semanas). Soy bueno en esfuerzos de 1 a 5 minutos, pero me apago después de 90 minutos.`,
    truthFtp: 240, best1Min: 360,
    fb: { note: 'Completé todo, pero la sesión larga se me hizo muy pesada.', rpe: 'as_planned', longRideRpe: 9, longRideDrift: 10 },
  },
  6: {
    title: 'Bajar de peso × sin banda de FC', age: 45, weight: 95, sex: null, ftp: null, hrMax: 185, discipline: 'other',
    experienceLevel: 'returning_or_new_to_app', generalFitnessLevel: 'sedentary', yearsRiding: 1, competes: false, category: null,
    hours: 4, days: ['mon', 'wed', 'fri', 'sat'], maxMin: null, injuries: null,
    goal: () => 'Quiero bajar 10 kg. No tengo banda de frecuencia cardiaca.',
    truthFtp: 170, best1Min: 235, noHr: true,
    fb: { note: 'Completé todo.', rpe: 'as_planned' },
  },
  7: {
    title: 'Clase tipo spinning × desestrés', age: 35, weight: 62, sex: 'F', ftp: null, hrMax: 185, discipline: 'other',
    experienceLevel: 'returning_or_new_to_app', generalFitnessLevel: 'active_other_sport', yearsRiding: 0, competes: false, category: null,
    hours: 3, days: ['mon', 'wed', 'fri', 'sat'], maxMin: 45, injuries: null,
    goal: () => 'Me gustan las clases de indoor cycling con música. Quiero entrenar 3-4 veces por semana 45 min para desestresarme, sin meta de rendimiento.',
    truthFtp: 145, best1Min: 200,
    fb: { note: 'Hice 2 de 4 sesiones; me aburrí en las sesiones planas.', completeFraction: 0.5, rpe: 'as_planned' },
  },
  8: {
    title: 'Gran fondo × master en altitud', age: 56, weight: 76, sex: null, ftp: 210, ftpAgeDays: 45, hrMax: 185, discipline: 'road',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 20, competes: false, category: null,
    hours: 6, days: ['tue', 'thu', 'sat', 'sun'], maxMin: null, injuries: null,
    goal: () => `Gran fondo a nivel del mar el ${inWeeks(12)} (en 12 semanas). Vivo y entreno en Toluca, a unos 2,600 m de altitud.`,
    truthFtp: 210, best1Min: 285,
    fb: { note: 'Completé todo, pero con cansancio acumulado al final de la semana.', rpe: 'rising' },
  },
  9: {
    title: 'Maratón MTB × diésel', age: 44, weight: 80, sex: null, ftp: 220, ftpAgeDays: 30, hrMax: 185, discipline: 'mountain',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 10, competes: true, category: 'Master 40',
    hours: 9, days: ['mon', 'tue', 'thu', 'sat', 'sun'], maxMin: null, injuries: null,
    goal: () => `Maratón MTB el ${inWeeks(12)} (en 12 semanas). Aguanto 5 h a baja intensidad sin problema, pero me quedo en las subidas y en los cambios de ritmo.`,
    truthFtp: 220, best1Min: 290,
    fb: { note: 'Completé todo; la sesión de intervalos se me hizo muy dura.', rpe: 'as_planned', intervalsRpe: 9 },
  },
  10: {
    title: 'Ruta × FTP sólido, aeróbico dudoso', age: 30, weight: 68, sex: null, ftp: 265, ftpAgeDays: 20, hrMax: 185, discipline: 'road',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 6, competes: false, category: null,
    hours: 7, days: ['tue', 'wed', 'thu', 'sat', 'sun'], maxMin: null, injuries: null,
    goal: () => 'Mejorar en ruta. Tengo buen rendimiento en intervalos, pero la FC me deriva mucho en las rodadas de más de 2 horas.',
    truthFtp: 265, best1Min: 370,
    fb: { note: 'Completé todo. En la rodada larga tuve un desacople de FC de ~9%.', rpe: 'as_planned', longRideDrift: 9 },
  },
  11: {
    title: 'Triatlón × hace otro deporte', age: 37, weight: 70, sex: null, ftp: 240, ftpAgeDays: 30, hrMax: 185, discipline: 'other',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_other_sport', yearsRiding: 4, competes: true, category: '70.3 grupo de edad',
    hours: 6, days: ['tue', 'thu', 'sat', 'sun'], maxMin: null, injuries: null,
    goal: () => `Triatlón 70.3 el ${inWeeks(16)} (en 16 semanas). Corro 3 veces por semana y nado 2; para la bici tengo 6 h por semana.`,
    truthFtp: 240, best1Min: 320,
    fb: { note: 'Completé la bici, pero traigo las piernas cargadas por las carreras a pie.', rpe: 'above' },
  },
  12: {
    title: 'Maratón MTB × regresa de lesión', age: 39, weight: 75, sex: null, ftp: 250, ftpAgeDays: 180, hrMax: 185, discipline: 'mountain',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 8, competes: true, category: 'Master 30',
    hours: 6, days: ['tue', 'thu', 'sat', 'sun'], maxMin: null, injuries: 'Estuve 2 meses sin rodar por una lesión; ya me dieron de alta.',
    goal: () => 'Volver a competir en maratón MTB. Mi FTP de 250 W es de hace 6 meses; estuve 2 meses sin rodar por una lesión y ya me dieron de alta.',
    truthFtp: 215, best1Min: 290,
    fb: { note: 'Completé todo, pero la sesión de umbral se sintió casi imposible.', rpe: 'as_planned', thresholdRpe: 10, ergDetachedHits: 3 },
  },
  13: {
    title: 'Ruta × sobreentrenado', age: 34, weight: 71, sex: null, ftp: 260, ftpAgeDays: 30, hrMax: 185, discipline: 'road',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 9, competes: true, category: 'Élite amateur',
    hours: 12, days: ['mon', 'tue', 'wed', 'thu', 'sat', 'sun'], maxMin: null, injuries: null,
    goal: () => 'Seguir mejorando en ruta. Mi FC en reposo está 8 bpm arriba de lo normal, duermo mal y mi rendimiento está bajando.',
    truthFtp: 245, best1Min: 340,
    fb: { note: 'No pude terminar 2 sesiones y sigo durmiendo mal.', unfinished: 2, rpe: 'above' },
  },
  14: {
    title: 'Ultra / bikepacking × mixto indoor-outdoor', age: 42, weight: 77, sex: null, ftp: 220, ftpAgeDays: 30, hrMax: 185, discipline: 'gravel',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 10, competes: false, category: null,
    hours: 9, days: ['tue', 'wed', 'thu', 'sat'], maxMin: null, injuries: null,
    goal: () => `Ultra de 300 km (bikepacking) el ${inWeeks(16)} (en 16 semanas). Entre semana uso rodillo y el fin de semana hago una salida larga de 4-5 h afuera.`,
    truthFtp: 220, best1Min: 290,
    fb: { note: 'Completé todo; la salida del sábado (5 h) la subí como archivo.', rpe: 'as_planned', outdoorRide: { hours: 5, tss: 230 } },
  },
  15: {
    title: 'Criterium × poco tiempo', age: 27, weight: 66, sex: null, ftp: 255, ftpAgeDays: 30, hrMax: 185, discipline: 'road',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 5, competes: true, category: 'Cat 3',
    hours: 4, days: ['tue', 'wed', 'thu', 'sat'], maxMin: 60, injuries: null,
    goal: () => `Criteriums a partir del ${inWeeks(8)} (en 8 semanas). Solo tengo 4 sesiones de 1 h por semana.`,
    truthFtp: 255, best1Min: 380,
    fb: { note: 'Completé todo.', rpe: 'as_planned' },
  },
  16: {
    title: 'Gran fondo × betabloqueadores', age: 58, weight: 84, sex: null, ftp: null, hrMax: 185, discipline: 'road',
    experienceLevel: 'returning_or_new_to_app', generalFitnessLevel: 'active_cyclist', yearsRiding: 6, competes: false, category: null,
    hours: 5, days: ['tue', 'thu', 'sat', 'sun'], maxMin: null, injuries: 'Tomo betabloqueadores (medicamento para la presión).',
    goal: () => 'Prepararme para un gran fondo. Tomo betabloqueadores.',
    truthFtp: 180, best1Min: 245,
    fb: { note: 'Completé todo; la FC estuvo muy baja para el esfuerzo que sentía.', rpe: 'as_planned', lowHr: true },
  },
  17: {
    title: 'XCO × sobremotivado', age: 26, weight: 73, sex: null, ftp: null, hrMax: 185, discipline: 'mountain',
    experienceLevel: 'new_to_cycling', generalFitnessLevel: 'active_other_sport', yearsRiding: 0.25, competes: true, category: 'Novatos',
    hours: 15, days: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'], maxMin: null, injuries: null,
    goal: () => 'Llevo 3 meses rodando y quiero competir en XCO. Quiero entrenar 15 horas por semana.',
    truthFtp: 215, best1Min: 290,
    fb: { note: 'Completé todo, pero estoy muy cansado.', rpe: 'above' },
  },
  18: {
    title: 'XCO × menor de edad', age: 15, weight: 55, sex: null, ftp: null, hrMax: 185, discipline: 'mountain',
    experienceLevel: 'returning_or_new_to_app', generalFitnessLevel: 'active_cyclist', yearsRiding: 2, competes: true, category: 'Juvenil',
    hours: 8, days: ['mon', 'wed', 'thu', 'sat', 'sun'], maxMin: null, injuries: null,
    goal: () => 'Tengo 15 años y quiero competir en XCO.',
    truthFtp: 180, best1Min: 250,
    fb: { note: 'Completé todo.', rpe: 'as_planned' },
  },
  19: {
    title: 'Ruta × datos contradictorios', age: 40, weight: 70, sex: null, ftp: 320, ftpAgeDays: 30, hrMax: 230, discipline: 'road',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 5, competes: false, category: null,
    hours: 7, days: ['tue', 'wed', 'thu', 'sat', 'sun'], maxMin: null, injuries: null,
    goal: () => 'Mejorar en ruta. Mi mejor potencia de 20 minutos es de 210 W.',
    truthFtp: 200, best1Min: 275,
    fb: { note: 'Completé todo.', rpe: 'as_planned' },
  },
  20: {
    title: 'Gravel × inconsistente', age: 36, weight: 79, sex: null, ftp: 225, ftpAgeDays: 30, hrMax: 185, discipline: 'gravel',
    experienceLevel: 'experienced', generalFitnessLevel: 'active_cyclist', yearsRiding: 5, competes: false, category: null,
    hours: 6, days: ['tue', 'wed', 'thu', 'sat', 'sun'], maxMin: null, injuries: null,
    goal: () => `Carrera de gravel el ${inWeeks(12)} (en 12 semanas).`,
    truthFtp: 225, best1Min: 300,
    fb: { note: 'Falté al 40% de las sesiones por trabajo.', completeFraction: 0.6, rpe: 'as_planned' },
  },
  21: {
    title: 'Sin meta clara × novato', age: 31, weight: 68, sex: null, ftp: null, hrMax: 185, discipline: 'road',
    experienceLevel: 'new_to_cycling', generalFitnessLevel: 'active_other_sport', yearsRiding: 0, competes: false, category: null,
    hours: 4, days: ['tue', 'thu', 'sat'], maxMin: null, injuries: null,
    goal: () => 'Quiero estar más fuerte.',
    truthFtp: 185, best1Min: 250,
    fb: { note: 'Completé todo.', rpe: 'as_planned' },
  },
  // Reproducción limpia de E-13: arranque en viernes con solo días entre semana ya pasados
  99: {
    title: 'Repro E-13 × días ya pasados', age: 31, weight: 68, sex: null, ftp: null, hrMax: 185, discipline: 'road',
    experienceLevel: 'new_to_cycling', generalFitnessLevel: 'active_other_sport', yearsRiding: 0, competes: false, category: null,
    hours: 3, days: ['tue', 'wed', 'thu'], maxMin: null, injuries: null,
    goal: () => 'Quiero estar más fuerte.',
    truthFtp: 185, best1Min: 250,
    fb: { note: 'Completé todo.', rpe: 'as_planned' },
  },
};
